## Print Elements of Array

**Problem**: Given 1X1 Array:

```
arr_1d = [53, 78, 90, 12, 15, 65, 44, 32, 29, 36]
```

1. Print 3rd and 9th element of the array.
2. Change  3rd and 9th element to 100.


In [1]:
# write code here
import numpy as np

arr_1d = np.array([53, 78, 90, 12, 15, 65, 44, 32, 29, 36])
print(arr_1d[2])
print(arr_1d[8])
arr_1d[2] = 100
arr_1d[8] = 100
print(arr_1d)

90
29
[ 53  78 100  12  15  65  44  32 100  36]


## Update Diagonal Elements of Multidimensional Array

**Problem**: Given a 3x3 array, change all the diagonal elements of the matrix to 0.

```

arr_2d = [[1,2,3],
          [4,5,6],
          [7,8,9]]
```





In [7]:
#Write code here

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

for i in range(len(arr_2d)):
  arr_2d[i][i] = 0

print(arr_2d)

[[0 2 3]
 [4 0 6]
 [7 8 0]]


## Numbers of Rows & Column

**Problem**: Write a program to find the number of rows and columns present in the matrix given below.
Note: Initialize the matrix using NumPy.

```
 A= [[9,5,6,1,-2],
    [3,-8,1,2,0],
    [6,9,3,3,5]]
```



In [3]:
# write code here
A = [[9,5,6,1,-2],
    [3,-8,1,2,0],
    [6,9,3,3,5]]

rows = len(A)
cols = len(A[0])
print(f"number of rows: {rows}")
print(f"number of colums: {cols}")

number of rows: 3
number of colums: 5


## Scalar Multiplication

**Problem**: Print each element of the following matrix. Initialize the matrix using NumPy.  <br />
Also, multiply the matrix with n = 150 and print the matrix after multiplication.
   
```
 B=[[-8,0,2,4],[5,2,-1,7]]
```


   

In [6]:
B= np.array([[-8,0,2,4],[5,2,-1,7]])
n = 150
C = np.multiply(B,n)
for i in range(2):
  for y in range(4):
    print(f"Element {(i+1)*(y+1)} is {B[i][y]}")
print('\n',C)

Element 1 is -8
Element 2 is 0
Element 3 is 2
Element 4 is 4
Element 2 is 5
Element 4 is 2
Element 6 is -1
Element 8 is 7

 [[-1200     0   300   600]
 [  750   300  -150  1050]]
